defaults: &defaults
  host: localhost
  port: 27017

development:
  <<: *defaults
  database: wieners
  host: flame.mongohq.com
  port: 27067
  username: wieners
  password: MetaLab2010

test:
  <<: *defaults
  database: wieners_test

# set these environment variables on your prod server
production:
  <<: *development
  database: wieners_production
